include: package:pedantic/analysis_options.yaml 
#include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: false
    file_names: false

analyzer:
  exclude: [example/**]