name: flutter_auto_export
description: A new Flutter package that allows you to auto export types globally.
version: 1.1.0
homepage: https://github.com/AlbertoMonteiro/FlutterAutoExport

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  analyzer: ">=0.38.5 <0.40.0"
  source_gen: ^0.9.6
  build: ^1.3.0
  build_resolvers: ^1.3.10
  meta: ^1.2.2
  glob: ^1.2.0
